### ISSUE TITLE
Cursor: pointer

### ISSUE THREAD

**Issue by patik** [tevko/clickSuck#2]
Perhaps it's worth mentioning that if you set the style `cursor: pointer` on an element it will receive `click` events automatically without needing JS.

**Comment by tevko** [comment]
@patik unfortunately that is not always the case. cursor: pointer will solve some problems, but the bug is a lot larger than that, and elements that are not links or buttons can still not fire click events. I've used the css solution with success on some elements, and then have seen it not work on others, on the same page!
